<?xml version="1.0" encoding="UTF-8"?>
<project name="PD1_Stankevics_24" default="compile" basedir=".">
    
    <property name="src.dir" value="src"/>
    <property name="build.dir" value="build"/>
    <property name="docs.dir" value="docs"/>
    
    <target name="init">
        <mkdir dir="${build.dir}"/>
        <mkdir dir="${docs.dir}"/>
    </target>
    
    <target name="compile" depends="init">
        <javac srcdir="${src.dir}" destdir="${build.dir}" includeantruntime="false"/>
    </target>
    
    <target name="javadoc" depends="init">
        <javadoc sourcepath="${src.dir}" destdir="${docs.dir}" private="true" access="private">
            <fileset dir="${src.dir}" includes="**/*.java"/>
        </javadoc>
    </target>
    
    <target name="clean">
        <delete dir="${build.dir}"/>
        <delete dir="${docs.dir}"/>
    </target>
    
</project>